### ISSUE TITLE
Protocol Nits

### ISSUE THREAD

**Issue by exteradox** [BitcoinUnlimited/BitcoinCashSpecification#35]
Implemented part of the protocol from this documentation. Found some nits:

[feefilter](https://github.com/BitcoinUnlimited/BitcoinCashSpecification/blob/master/protocol/network/messages/feefilter.md)
* Message command is "feefilter" not "filterfee".
* Message contains the minimum fee per 1000 bytes, not per byte.

[block](https://github.com/BitcoinUnlimited/BitcoinCashSpecification/blob/master/protocol/network/messages/block.md)
* Timestamp field has 4 bytes, not 8 bytes.

**Comment by thesquaregroot** [comment]
@exteradox do the above commits referencing this issue sufficiently address your concerns?

**Comment by exteradox** [comment]
Yes. Thanks!
